# Generated by Django 2.2.7 on 2021-06-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabSeller',
            fields=[
                ('cod_seller', models.AutoField(primary_key=True, serialize=False)),
                ('name_seller', models.CharField(max_length=100)),
                ('activo_seller', models.CharField(max_length=1)),
                ('feccre_seller', models.DateField()),
                ('commision_perce_seller', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tab_seller',
                'managed': False,
            },
        ),
    ]
