# Generated by Django 2.2.7 on 2021-06-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('cod_produc', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Codigo Producto')),
                ('name_produc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Producto')),
            ],
        ),
    ]
